name: openiap_gql_codegen
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  gql: ^0.13.1

dev_dependencies:
  build_runner: ^2.4.6
  graphql_codegen: ^0.14.1

# Point graphql_codegen to the shared schema files
graphql_codegen:
  schema:
    - ../../src/type.graphql
    - ../../src/type-ios.graphql
    - ../../src/type-android.graphql
    - ../../src/api.graphql
    - ../../src/api-ios.graphql
    - ../../src/api-android.graphql
  output: lib/generated/
